export const car = [
  {
    name: "Accent",
    images: ["/car/accentdark.png"],
    id: 'car1',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Accent",
    images: ["/car/accentgray.png"],
    id: 'car2',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Accent",
    images: ["/car/accentwhite.png"],
    id: 'car3',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Accent",
    images: ["/car/accentwhite.png"],
    id: 'car4',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Sunny",
    images: ["/car/sunny.png"],
    id: 'car5',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Sunny",
    images: ["/car/sunny.png"],
    id: 'car6',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Sunny",
    images: ["/car/sunny.png"],
    id: 'car7',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Creans",
    images: ["/car/creans.png"],
    id: 'car8',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Tiida",
    images: ["/car/tiida.png"],
    id: 'car9',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Tiida",
    images: ["/car/tiida.png"],
    id: 'car10',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Tiida",
    images: ["/car/tiida.png"],
    id: 'car11',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
  {
    name: "Isuzu",
    images: ["/car/isuzu.png"],
    id: 'car12',
    sim: 'abc',
    petrol: 700,
    oil: 'Good',
    history: 'sd',
    status: 'Ready',
    under: 'Osman',
    km: 25875,
    licence: 'valid',
    penalty: 'clear'
  },
]

export const docs = [
    { icon: 'ph:engine-thin', label: 'Status' },
    
    { icon: 'ph:gas-can-thin', label: 'Oil' },
    { icon: 'ph:gas-pump-thin', label: 'Petrol' },
    { icon: 'ph:sim-card-thin', label: 'SIM' },
    { icon: 'ph:camera-thin', label: 'Penalty' },
    { icon: 'arcticons:permissionsmanager', label: 'Licence' },
    { icon: 'ph:arrow-counter-clockwise-thin', label: 'History' },
    { icon: 'ph:ruler-thin', label: 'KM' },
    
    
  ]